language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python -m pytest --cov=allocation --cov=tests tests

after_script:
    - tools/run_pycodestyle.sh

# report coverage to coveralls.io
after_success:
    - coveralls

