language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install mypy

# command to run tests
script:
  - python -m pytest --cov=allocation --cov=tests tests
  - tools/run_mypy.sh

after_script:
    - tools/run_pycodestyle.sh

# report coverage to coveralls.io
after_success:
    - coveralls

